B3_C1/Controllers/Send_MailController.cs
using MailKit.Security;
using Microsoft.AspNetCore.Mvc;
using MimeKit;
using System.Threading.Tasks;
using B3_C1.Models;
using Microsoft.Extensions.Configuration;
using System.Net.Mail;
using System.Net;
using QuickMailer;
using System;

namespace B3_C1.Controllers
{
    public class Send_MailController : Controller
    {
        private readonly ISendMailService _emailSender;

        public Send_MailController(ISendMailService emailSender)
        {
            _emailSender = emailSender;
        }

        public async Task<IActionResult> Sendmail(EmailViewModel model)
        {
            await _emailSender.SendEmailAsync(model.ToEmail, model.Subject, model.Body);
            return View();
        }




        //----------------------------------------------------------
        public IActionResult SendEmail()
        {
            return View();
        }

        [HttpPost]
        public IActionResult SendEmail(EmailViewModel model)
        {
            string mgs = "Fail";

            try
            {
                Email email = new Email();
                bool isSend = email.SendEmail(model.ToEmail, Credential.Email, Credential.Password, model.Subject, model.Body);
                if (isSend)
                {
                    mgs = "Success.";
                }
                ViewBag.Mgs = mgs;
                return View();
            }
            catch (Exception e)
            {
                mgs = "Failed.";
                ViewBag.Mgs = mgs;
                return View();
            }
        }


        //[HttpPost]
        //public IActionResult SendEmail(EmailViewModel model)
        //{
        //    GuiMail(model.ToEmail,model.Subject,model.Body);
        //    return View(model);
        //}

        //public void GuiMail(string to,string subject,string body)
        //{
        //     string fromEmail = "jinbi2k1@gmail.com";
        //     string password = "Myfunction!@";

        //    MailMessage message = new MailMessage();
        //    message.From = new MailAddress(fromEmail);
        //    message.Subject = subject;
        //    message.To.Add(new MailAddress(to));
        //    message.Body = body;
        //    message.IsBodyHtml = true;

        //    var smtpClient = new SmtpClient()
        //    {
        //        Host = "smtp.gmail.com",
        //        Port = 587,// cổng kết nối smtp
        //        Credentials = new NetworkCredential(fromEmail,password),
        //        EnableSsl = true, // mã hóa dữ liệu khi gửi mail
        //        DeliveryMethod = SmtpDeliveryMethod.Network,//Đặt phthuc gửi mail là Network
        //        UseDefaultCredentials= false,


        //    };
        //    smtpClient.Send(message);

        //}

        public static class Credential
        {
            public static string Email = "jinbi2k1@gmail.com";
            public static string Password = "Myfunction!@";
        }

        //public ActionResult Send()
        //{
        //    return View();
        //}
        //[HttpPost]
        //public ActionResult Send(EmailViewModel model)
        //{
        //    try
        //    {
        //        Email email = new Email();
        //        email.SendEmail(model.ToEmail, model.Email, model.Password, model.Subject, model.Body);
        //        return View();
        //    }
        //    catch (Exception e)
        //    {
        //        Console.WriteLine(e);
        //        throw;
        //    }

        //}


    }
}

B3_C1/Controllers/UsersController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using DAL_B3.Context;
using DAL_B3.DomainClass;
using Microsoft.AspNetCore.Http;
using System.Security.Cryptography;

namespace B3_C1.Controllers
{
    public class UsersController : Controller
    {
        private readonly BaiTap2_DbContext _context;

        public UsersController(BaiTap2_DbContext context)
        {
            _context = context;
        }

        // GET: Users
        public async Task<IActionResult> Index(string filter)
        {
            var data = await _context.Users.Include(u => u.RoleId_Navigation).ToListAsync();

            if (filter == "2")
            {
                data = await _context.Users.Where(c => c.Status == true).ToListAsync();
            }
            else if (filter == "1")
            {
                data = await _context.Users.Where(c => c.Status == false).Include(u => u.RoleId_Navigation).ToListAsync();
            }
            else
            {
                data = await _context.Users.ToListAsync();
            }
            List<SelectListItem> isStatus = new List<SelectListItem>();

            isStatus.Add(new SelectListItem() { Text = "Tất cả", Value = "0" });
            isStatus.Add(new SelectListItem() { Text = "Đã xóa", Value = "1" });
            isStatus.Add(new SelectListItem() { Text = "Chưa xóa", Value = "2" });

            ViewData["isStatus"] = isStatus;

            return View(data);
        }


        // GET: Users/Create
        public IActionResult Create()
        {
            ViewData["RoleId"] = new SelectList(_context.Roles, "RoleId", "RoleCode");
            var userCreate = HttpContext.Session.GetString("UserName");
            if (userCreate != null)
            {
                return View();
            }
            return RedirectToAction("Login", "Login");
        }

        // POST: Users/Create
        // To protect from overposting attacks, enable the specific properties you want to bind to.
        // For more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create([Bind("UserId,UserName,Password,RoleId,Status,Description,CreatedPerson,Phone")] User user)
        {
            if (ModelState.IsValid)
            {
                
                user.Status = true;
                var userCreate = HttpContext.Session.GetString("UserName");
                user.CreatedPerson = userCreate;
                _context.Add(user);
                await _context.SaveChangesAsync();
                return RedirectToAction(nameof(Index));
            }
            ViewData["RoleId"] = new SelectList(_context.Roles, "RoleId", "RoleCode", user.RoleId);
            return View(user);
        }

        // GET: Users/Edit/5
        public async Task<IActionResult> Edit(Guid? id)
        {
            var userCreate = HttpContext.Session.GetString("UserName");
            if (userCreate != null)
            {
                if (id == null)
                {
                    return NotFound();
                }

                var user = await _context.Users.FindAsync(id);
                if (user == null)
                {
                    return NotFound();
                }
                ViewData["RoleId"] = new SelectList(_context.Roles, "RoleId", "RoleCode", user.RoleId);
                return View(user);
            }
            else
            {
                return RedirectToAction("Login", "Login");
            }
           
        }

        // POST: Users/Edit/5
        // To protect from overposting attacks, enable the specific properties you want to bind to.
        // For more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit(Guid? id, [Bind("UserId,UserName,Password,RoleId,Status,Description,CreatedPerson,Phone")] User user)
        {
            if (id != user.UserId)
            {
                return NotFound();
            }

            if (ModelState.IsValid)
            {
                try
                {
                    _context.Update(user);
                    await _context.SaveChangesAsync();
                }
                catch (DbUpdateConcurrencyException)
                {
                    if (!UserExists(user.UserId))
                    {
                        return NotFound();
                    }
                    else
                    {
                        throw;
                    }
                }
                return RedirectToAction(nameof(Index));
            }
            ViewData["RoleId"] = new SelectList(_context.Roles, "RoleId", "RoleCode", user.RoleId);
            return View(user);
        }

        // GET: Users/Delete/5
        public async Task<IActionResult> Delete(Guid? id)
        {
            var userCreate = HttpContext.Session.GetString("UserName");
            if (userCreate != null)
            {
                if (id == null)
                {
                    return NotFound();
                }

                var user = await _context.Users
                    .Include(u => u.RoleId_Navigation)
                    .FirstOrDefaultAsync(m => m.UserId == id);
                if (user == null)
                {
                    return NotFound();
                }

                return View(user);
            }
            return RedirectToAction("Login", "Login");
            
        }

        // POST: Users/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> DeleteConfirmed(Guid? id)
        {
            var user = await _context.Users.FindAsync(id);
            user.Status = false;
            _context.Users.Update(user);
            await _context.SaveChangesAsync();
            return RedirectToAction(nameof(Index));
        }

        private bool UserExists(Guid? id)
        {
            return _context.Users.Any(e => e.UserId == id);
        }
    }
}

B3_C1/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - B3_C1</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" />
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
            <div class="container">
                <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index">B3_C1</a>
                <button class="navbar-toggler" type="button" data-toggle="collapse" data-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex justify-content-between">
                    <ul class="navbar-nav flex-grow-1">
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Index">Home</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Users" asp-action="Index">Bài2</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="UsersStored" asp-action="Index">Bài2 Stored</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Group" asp-action="Index">Bài3</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="GroupStored" asp-action="Index">Bài 3 stored</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Send_Mail" asp-action="SendEmail">SendMail</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="SMSs" asp-action="Index">Bài 4</a>
                        </li>
                        <li class="nav-item">
                            @if (User.Identity.IsAuthenticated == false)
                            {
                                <a class="nav-link" href="/dang-nhap.html">
                                    <i class="icon ion-happy-outline"></i>
                                    <span>Đăng nhập</span>
                                    <span class="square-8"></span>
                                </a>
                            }
                            else
                            {
                                <a class="nav-link" href="/dang-xuat.html">
                                    <i class="icon ion-ios-information-outline"></i>
                                    <span> Đăng xuất</span>
                                    <span class="square-8"></span>
                                </a>
                            }
                        </li>
                    </ul>
                </div>
            </div>
        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; 2023 - B3_C1 - <a asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
        </div>
    </footer>
    <script src="~/jquery.min.js"></script>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/lib/jquery-validation/dist/jquery.validate.min.js"></script>
    <script src="~/lib/jquery-validation-unobtrusive/jquery.validate.unobtrusive.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>